### PR TITLE
Find mismatch

### PR DESCRIPTION
**Pull request by andrewpeterson99**
Finds indices of mismatches using a hard-vote-esque method (soft-vote can be implemented in future using predict_proba for each model).

### CODE REVIEW

**Review by MSBradshaw — CHANGES_REQUESTED** [review]
Code looks good, but why has subchallenge1.csv been regenerated and why is is almost perfectly opposite of the previous one?

**Comment by andrewpeterson99** [comment]
Deleted subchannelege1.csv so that changes don't occur on pull request

**Comment by andrewpeterson99** [comment]
Just updated w/a new commit that contains probability value output w/an algorithm by Dallas™.

**Comment by MSBradshaw** [comment]
Now subchallenge1.csv one is completely gone, re add the old one to your repo, commit and push it again.

**Comment by andrewpeterson99** [comment]
Added original subchallenge_1.csv.

**Review by MSBradshaw — APPROVED** [review]

**Pull request merged**
